///////////////////////////////////////////////////////////
//  Ejemplar.cs
//  Implementation of the Class Ejemplar
//  Generated by Enterprise Architect
//  Created on:      30-nov-2014 06:35:59 p.m.
//  Original author: jonatan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace RN {
	public class Ejemplar {

		private int numero;

		public Ejemplar(){

		}

		~Ejemplar(){

		}

	}//end Ejemplar

}//end namespace Clases