///////////////////////////////////////////////////////////
//  Libro.cs
//  Implementation of the Class Libro
//  Generated by Enterprise Architect
//  Created on:      30-nov-2014 06:36:02 p.m.
//  Original author: jonatan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace RN
{
    public class Libro
    {
        private int codigo;
        private string autor;
        private string titulo;
        private string genero;
        private int isbn;
        private string editorial;
        private List<Ejemplar> ejemplares;

        public Libro(int cod, string a, string t, string g, int isbn, string ed)
        {
            codigo = cod;
            autor = a;
            titulo = t;
            genero = g;
            this.isbn = isbn;
            editorial = ed;
            ejemplares = new List<Ejemplar>();
        }

        public Libro(string t, string g, string isbn, int cantEjemplares)
        {
            titulo = t;
            genero = g;
            this.isbn = isbn;
            ejemplares = new List<Ejemplar>();
            Ejemplar ejem;
            for (int i = 0; i < cantEjemplares; i++)
            {
                ejem = new Ejemplar(i + 1, this, "DISPONIBLE");
                ejemplares.Add(ejem);
            }

        }

        public int Codigo
        {
            get { return codigo; }
            set { codigo = value; }
        }
        public string Autor
        {
            get { return autor; }
            set { autor = value; }
        }
        public string Titulo
        {
            get { return titulo; }
            set { titulo = value; }
        }
        public string Genero
        {
            get { return genero; }
            set { genero = value; }
        }
        public int Isbn
        {
            get { return isbn; }
            set { isbn = value; }
        }
        public string Editorial
        {
            get { return editorial; }
            set { editorial = value; }
        }
        public List<Ejemplar> Ejemplares
        {
            get { return ejemplares; }
            set { ejemplares = value; }
        }


        ~Libro()
        {

        }

    }//end Libro

}//end namespace Clases