///////////////////////////////////////////////////////////
//  Libro.cs
//  Implementation of the Class Libro
//  Generated by Enterprise Architect
//  Created on:      30-nov-2014 06:36:02 p.m.
//  Original author: jonatan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace RN {
	public class Libro {
        private string titulo;
		private string autor;
		private int codigo;
		private string isbn;
        private string tema;

		public Libro(){

          

		}

		~Libro(){

		}

	}//end Libro

}//end namespace Clases