///////////////////////////////////////////////////////////
//  Socio.cs
//  Implementation of the Class Socio
//  Generated by Enterprise Architect
//  Created on:      30-nov-2014 06:37:04 p.m.
//  Original author: jonatan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace RN {
	public abstract class Socio {

		private string correo;
		private string Nombre;
		private int Numero;

		public Socio(){

		}

		~Socio(){

		}

	}//end Socio

}//end namespace Clases